### ISSUE TITLE
template config file from manifest.toml

### ISSUE THREAD

**Issue by aymericdelab** [edisontim/haiku#5]
a template of the config file should be automatically created by inputting the manifest.toml.

The dev just needs to add the necessary events to it's contracts, then sozo build and create the manifest.

Once the manifest is created, all events that have the "haiku" namespace, are gonna get added automatically to the haiku config.

```
#[dojo::model(namespace: "haiku")]
```

should be working with a cli like "haiku config --path-to-manifest" --namespace haiku

**Comment by aymericdelab** [comment]
down to take this one

**Comment by edisontim** [comment]
Closed by #20
